#include "levels.h"

// enum TileType {
//   FREE, 1
//   TOP_LEFT_CORNER,2
//   HORIZONTAL_WALL,3
//   TOP_RIGHT_CORNER,4
//   VERTICAL_WALL,5
//   BOTTOM_RIGHT_CORNER,6
//   BOTTOM_LEFT_CORNER 7
// };
const int Levels::one[] = {
  TOP_LEFT_CORNER, HORIZONTAL_WALL, T_JUNCTION, HORIZONTAL_WALL, HORIZONTAL_WALL, HORIZONTAL_WALL, HORIZONTAL_WALL, HORIZONTAL_WALL, HORIZONTAL_WALL, TOP_RIGHT_CORNER,
  VERTICAL_WALL, FREE, VERTICAL_WALL, FREE, FREE, FREE, FREE, FREE, FREE, VERTICAL_WALL,
  VERTICAL_WALL, FREE, VERTICAL_WALL, FREE, FREE, FREE, FREE, FREE, FREE, VERTICAL_WALL,
  VERTICAL_WALL, FREE, FREE, FREE, FREE, FREE, FREE, FREE, FREE, VERTICAL_WALL,
  RIGHT_T_JUNCTION, HORIZONTAL_WALL, HORIZONTAL_WALL, FREE, FREE, FREE, FREE, FREE, FREE, VERTICAL_WALL,
  VERTICAL_WALL, FREE, FREE, FREE, FREE, FREE, FREE, FREE, FREE, VERTICAL_WALL,
  VERTICAL_WALL, FREE, FREE, FREE, FREE, FREE, CROSSROADS, HORIZONTAL_WALL, HORIZONTAL_WALL, LEFT_T_JUNCTION,
  VERTICAL_WALL, FREE, FREE, FREE, FREE, FREE, FREE, FREE, FREE, VERTICAL_WALL,
  VERTICAL_WALL, FREE, VERTICAL_WALL, FREE, FREE, FREE, FREE, FREE, FREE, VERTICAL_WALL,
  BOTTOM_LEFT_CORNER, HORIZONTAL_WALL, INVERTED_T_JUNCTION, HORIZONTAL_WALL, HORIZONTAL_WALL, HORIZONTAL_WALL, HORIZONTAL_WALL, HORIZONTAL_WALL, HORIZONTAL_WALL, BOTTOM_RIGHT_CORNER
};

// 2, 3, 3, 3, 3, 3, 3, 3, 3, 4,
// 5, 1, 1, 1, 1, 1, 1, 1, 1, 5,
// 5, 1, 1, 1, 1, 1, 1, 1, 1, 5,
// 5, 1, 1, 1, 1, 1, 1, 1, 1, 5,
// 5, 1, 1, 1, 1, 1, 1, 1, 1, 5,
// 5, 1, 1, 1, 1, 1, 1, 1, 1, 5,
// 5, 1, 1, 1, 1, 1, 1, 1, 1, 5,
// 5, 1, 1, 1, 1, 1, 1, 1, 1, 5,
// 5, 1, 1, 1, 1, 1, 1, 1, 1, 5,
// 7, 3, 3, 3, 3, 3, 3, 3, 3, 6
