#include "levels.h"

const int Levels::one[] = {
  TOP_LEFT_CORNER, HORIZONTAL_WALL, HORIZONTAL_WALL, HORIZONTAL_WALL, TOP_RIGHT_CORNER,
  VERTICAL_WALL, FREE, FREE, FREE, VERTICAL_WALL,
  VERTICAL_WALL, FREE, FREE, FREE, VERTICAL_WALL,
  VERTICAL_WALL, FREE, FREE, FREE, VERTICAL_WALL,
  BOTTOM_LEFT_CORNER, HORIZONTAL_WALL, HORIZONTAL_WALL, HORIZONTAL_WALL, BOTTOM_RIGHT_CORNER
};
